import javax.swing.*;

public class form1 {
    private JPanel panel1;
    private JTabbedPane tabbedPane1;
    private JPanel taborder;
    private JPanel tabclientdetails;
    private JTextField clientcontacttextfield;
    private JTextField clientnametextfield;
    private JTextField clientaddresstextfield;
    private JTextField deliverydaystextfield;
    private JButton saveCustomerInfoButton;
    private JButton resetButton;
    private JComboBox comboboxclientpreset;
    private JLabel labelclientpreset;
    private JSpinner spinnercucumbers;
    private JTextPane additionalCustomOrderWillTextPane;
    private JButton saveOrderButton;
    private JButton resetOrderButton;
    private JCheckBox haveCustomOrderCheckBox;
    private JTable tableordertotalandtransport;
    private JButton deleteOrderButton;
    private JButton saveOrderButton1;
    private JLabel labeldeliverydays;
    private JLabel labelclientaddress;
    private JLabel labelclientname;
    private JLabel labelclientcontact;
    private JPanel tabtotals;
    private JSpinner spinnerdetergentbags;
    private JSpinner spinnerapples;
    private JSpinner spinnerbread;
    private JSpinner spinneroil;
    private JSpinner spinnertomatoes;
    private JSpinner spinnerapricots;
    private JLabel labelcucumbers;
    private JLabel labelapples;
    private JLabel labelbread;
    private JLabel labeloil;
    private JLabel labelwater;
    private JSpinner spinnerwater;
    private JLabel labeldetergent;
    private JLabel labelapricots;
    private JLabel labeltomatoes;
    private JLabel labelcopyright2022;
}
